### ISSUE TITLE
Next stage icons no longer show up in navigation at the end of a stage

### ISSUE THREAD

**Issue by raf-42** [bo0tzz/PeglinGPS#8]
The map portion still works great, but the icons within the actual level when you're going to navigate are now missing. It doesn't matter if you have the relevant node on the map green or not.

![Peglin_2022-12-26_16-45-06](https://user-images.githubusercontent.com/3266377/209585011-1caa2092-7884-4d1b-ae81-1c27252b4194.png)

Thanks for the otherwise-excellent mod! I consider it mandatory to have when playing Peglin

**Comment by bo0tzz** [comment]
Thanks very much for the report! This is fixed in the latest release.
